#Author: Synthbot
---
resources:
- name: concourse-sandbox
  icon: ((git-icon))
  type: git
  source:
    uri: https://github.com/Synthbot/concourse-sandbox.git
    branch: develop

- name: ubuntu-latest
  icon: docker
  type: docker-image
  source:
      repository: ubuntu
      tag: latest

jobs:
- name: print-directories-of-image
  public: true
  
  build_log_retention:
    builds: 2
    days: 7
  
  plan:
  - in_parallel:
    - get: ubuntu-latest
      trigger: true
    - get: concourse-sandbox
      trigger: true
  - task: print-directories
    privileged: true
    image: ubuntu-latest
    input_mapping: {github-source: concourse-sandbox, docker-base-image: ubuntu-latest}
    file: concourse-sandbox/tasks/print-directories/print-directories.yml
    