#Author: Synthbot
---
resources:
- name: concourse-sandbox
  icon: ((git-icon))
  type: git
  source:
    uri: https://github.com/Synthbot/concourse-sandbox.git
    branch: master

- name: alpine-latest
  icon: docker
  type: docker-image
  source:
      repository: alpine
      tag: "latest"

jobs:
- name: print-directories
  public: true
  
  build_log_retention:
    builds: 2
    days: 7
  
  plan:
  - in_parallel:
    - get: alpine-latest
      trigger: true
    - get: concourse-sandbox
      trigger: true
  - task: print-directories
    privileged: true
    input-mapping: [source: concourse-sandbox, docker-base-image: alipine-latest]
    file: concourse-sandbox/tasks/print-directories/print-directories.yml