---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: alpine
    tag: latest

inputs:
  - name: github-source
  - name: docker-base-image
run:
  path: github-source/tasks/print-directories/print-directories.sh